Repository quadratic-funding/mpc-phase2-suite, pull requests merged in 2022-12, with the labels that each got.

#223 Bootstrap basic data generators and utilities for testing
  packages/actions/test/data/generators.ts
  packages/actions/test/data/samples.ts
  packages/actions/test/index.test.ts
  packages/actions/test/utils/index.ts
  packages/actions/types/index.ts
  packages/phase2cli/src/lib/firebase.ts
Labels: Feature 🪄, Test 🧪

#222 Use re-export instead of import/export
  packages/actions/src/index.ts
  packages/backend/src/functions/index.ts
  packages/phase2cli/src/commands/index.ts
Labels: Enhancement 🥋

#229 Update CI action for running test
  .github/workflows/test-ci.yaml
  package.json
Labels: DevOps ⚙

#227 Update Node.js version requirement in README.md
  README.md
Labels: Documentation 📚

#228 Fix build failure of website
  .github/workflows/website.yaml
Labels: DevOps ⚙

#236 Workaround for SSL error
  .github/workflows/deploy-dev.yaml
Labels: bug 🪲

#237 Add missing passwordless sudo to command for getting privileges
  .github/workflows/deploy-dev.yaml
Labels: bug 🪲

#241 ci: publish latest development to npm
  .github/workflows/test-ci.yaml
Labels: DevOps ⚙

#238 chore: add a pre-commit hook to enforce linting automatically
  .husky/pre-commit
  README.md
  package.json
  yarn.lock
Labels: DevOps ⚙

#234 feat(setup): decoupling setup from the cli
  packages/actions/.env.test.default
  packages/actions/src/core/setup/index.ts
  packages/actions/src/helpers/storage.ts
  packages/actions/src/index.ts
  packages/actions/test/index.test.ts
  packages/actions/test/setup.test.ts
  packages/actions/types/index.ts
  packages/phase2cli/src/commands/setup.ts
Labels: Enhancement 🥋

#245 refactor(storage helpers): refactoring storage helpers ..
  packages/actions/src/helpers/storage.ts
  packages/actions/src/index.ts
  packages/actions/test/index.test.ts
  packages/actions/test/setup.test.ts
  packages/actions/test/utils/index.ts
  packages/phase2cli/src/commands/setup.ts
  packages/phase2cli/src/lib/utils.ts
Labels: bug 🪲

#254 Add Firebase Emulator for CI testing
  .github/workflows/test-ci-dev.yaml
  .github/workflows/test-ci-prod.yaml
  package.json
  packages/actions/test/index.test.ts
  packages/actions/test/utils/index.ts
  packages/backend/.firebaserc
  packages/backend/firebase.json
  packages/backend/package.json
Labels: DevOps ⚙, Test 🧪
