Repository quadratic-funding/mpc-phase2-suite, pull requests merged in 2023-01, with the labels that each got.

#247 refactor(contribute): refactoring the contribute command
  packages/actions/src/core/contribute/index.ts
  packages/actions/src/core/lib/utils.ts
  packages/actions/src/helpers/constants.ts
  packages/actions/src/helpers/query.ts
  packages/actions/src/helpers/storage.ts
  packages/actions/src/helpers/verification.ts
  packages/actions/src/index.ts
  packages/actions/test/contribute.test.ts
  packages/actions/test/setup.test.ts
  packages/backend/package.json
  packages/backend/src/functions/waitingQueue.ts
  packages/phase2cli/src/commands/contribute.ts
  packages/phase2cli/src/commands/finalize.ts
  packages/phase2cli/src/commands/setup.ts
  packages/phase2cli/src/lib/firebase.ts
  packages/phase2cli/src/lib/listeners.ts
  packages/phase2cli/src/lib/prompts.ts
  packages/phase2cli/src/lib/storage.ts
  packages/phase2cli/src/lib/utils.ts
Labels: Refactoring ♻

#261 Updated refactoring of `clean` command
  packages/actions/src/helpers/files.ts
  packages/actions/src/index.ts
  packages/actions/test/clean.test.ts
  packages/phase2cli/src/commands/clean.ts
  packages/phase2cli/src/commands/contribute.ts
  packages/phase2cli/src/commands/finalize.ts
  packages/phase2cli/src/commands/setup.ts
  packages/phase2cli/src/index.ts
  packages/phase2cli/src/lib/auth.ts
  packages/phase2cli/src/lib/storage.ts
  packages/phase2cli/src/lib/utils.ts
Labels: bug 🪲, Refactoring ♻

#262 Fix Refactor/Observe
  packages/phase2cli/src/commands/observe.ts
  packages/phase2cli/src/lib/queries.ts
Labels: Refactoring ♻

#257 chore: apply default value to config file
  packages/backend/.default.env
Labels: Enhancement 🥋

#259 chore: bump firebase-functions to 4.1.1
  packages/backend/package.json
  yarn.lock
Labels: dependencies 📦

#258 fix: remove oauth token when it is invalid
  packages/phase2cli/src/commands/auth.ts
Labels: bug 🪲

#260 ci: cache nodejs dependencies
  .github/workflows/deploy-dev.yaml
  .github/workflows/test-ci-dev.yaml
  .github/workflows/test-ci-prod.yaml
Labels: DevOps ⚙

#256 chore: remove unnecessary values
  packages/backend/.default.env
  packages/backend/firebase.json
  packages/backend/storage.rules
  packages/phase2cli/.env.default
  packages/phase2cli/README.md
Labels: Enhancement 🥋

#267 Missing parameter for query method
  .github/workflows/deploy-dev.yaml
  .github/workflows/test-ci-dev.yaml
  .github/workflows/test-ci-prod.yaml
  packages/backend/firestore.indexes.json
  packages/phase2cli/src/commands/setup.ts
  packages/phase2cli/src/lib/prompts.ts
  packages/phase2cli/src/lib/queries.ts
  packages/phase2cli/src/lib/utils.ts
Labels: bug 🪲

#269 Missing path update when using a pre-computed zkey
  packages/phase2cli/src/commands/setup.ts
Labels: bug 🪲

#274 chore(changelog): add CHANGELOG
  .conventional-changelog.config.json
  CHANGELOG.md
Labels: Documentation 📚, Enhancement 🥋

#270 Optimized modularization of `auth` command
  .eslintrc.json
  .github/workflows/deploy-dev.yaml
  .github/workflows/test-ci-dev.yaml
  .github/workflows/test-ci-prod.yaml
  jest.json
  package.json
  packages/actions/.env.test.default
  packages/actions/package.json
  packages/actions/src/core/auth/index.ts
  packages/actions/src/core/lib/utils.ts
  packages/actions/src/helpers/firebase.ts
  packages/actions/src/helpers/query.ts
  packages/actions/src/index.ts
  packages/actions/test/clean.test.ts
  packages/actions/test/data/generators.ts
  packages/actions/test/data/samples.ts
  packages/actions/test/e2e/00-authentication.test.ts
  packages/actions/test/e2e/01-setup.test.ts
  packages/actions/test/e2e/02-contribution.test.ts
  packages/actions/test/e2e/03-finalization.test.ts
  packages/actions/test/e2e/04-clean.test.ts
  packages/actions/test/finalize.test.ts
  packages/actions/test/index.test.ts
  packages/actions/test/setup.test.ts
  packages/actions/test/unit/firebase.test.ts
  packages/actions/test/utils/authentication.ts
  packages/actions/test/utils/configs.ts
  packages/actions/test/utils/index.ts
  packages/actions/types/index.ts
  packages/backend/firestore.indexes.json
  packages/phase2cli/package.json
  packages/phase2cli/src/commands/auth.ts
  packages/phase2cli/src/commands/clean.ts
  packages/phase2cli/src/commands/contribute.ts
  packages/phase2cli/src/commands/finalize.ts
  packages/phase2cli/src/commands/logout.ts
  packages/phase2cli/src/commands/observe.ts
  packages/phase2cli/src/commands/setup.ts
  packages/phase2cli/src/lib/auth.ts
  packages/phase2cli/src/lib/authorization.ts
  packages/phase2cli/src/lib/commands.ts
  packages/phase2cli/src/lib/errors.ts
  packages/phase2cli/src/lib/firebase.ts
  packages/phase2cli/src/lib/localStorage.ts
  packages/phase2cli/src/lib/utils.ts
  packages/phase2cli/types/index.ts
  yarn.lock
Labels: Test 🧪, Refactoring ♻

#283 ci: add release workflow
  .conventional-changelog.config.json
  .github/workflows/release.yml
  .github/workflows/test-ci-prod.yaml
  CHANGELOG.md
  RELEASE.md
  lerna.json
Labels: DevOps ⚙

#287 chore(release): publish 0.1.0
  CHANGELOG.md
  lerna.json
  packages/actions/CHANGELOG.md
  packages/actions/package.json
  packages/backend/CHANGELOG.md
  packages/backend/package.json
  packages/phase2cli/CHANGELOG.md
  packages/phase2cli/package.json
  packages/website/CHANGELOG.md
  packages/website/package.json
Labels: DevOps ⚙

#290 docs: add CI status badge to README.md
  README.md
Labels: Documentation 📚

#286 Add missing environments for test prod action
  .github/workflows/test-ci-prod.yaml
Labels: bug 🪲, DevOps ⚙

#292 Switch from Github to email/pw authentication for testing
  .eslintrc.json
  packages/actions/test/data/samples.ts
  packages/actions/test/e2e/00-authentication.test.ts
  packages/actions/test/e2e/02-contribution.test.ts
  packages/actions/test/unit/firebase.test.ts
  packages/actions/test/utils/authentication.ts
  packages/backend/src/functions/auth.ts
Labels: Test 🧪, Refactoring ♻

#284 test(auth): added first tests for authentication
  packages/actions/test/e2e/00-authentication.test.ts
  packages/actions/test/utils/authentication.ts
  packages/actions/test/utils/index.ts
Labels: Test 🧪, High Priority 🔥

#294 ci: fix build failure of `npm-publish` job
  .github/workflows/test-ci-prod.yaml
Labels: bug 🪲, DevOps ⚙

#298 Fix a failure to publish npm
  .editorconfig
  .github/workflows/test-ci-prod.yaml
  .lintstagedrc.json
  package.json
  yarn.lock
Labels: bug 🪲, DevOps ⚙

#293 Optimize modularization of `setup` command
  packages/actions/src/helpers/constants.ts
  packages/actions/src/helpers/files.ts
  packages/actions/src/helpers/firebase.ts
  packages/actions/src/index.ts
  packages/phase2cli/src/commands/auth.ts
  packages/phase2cli/src/commands/clean.ts
  packages/phase2cli/src/commands/contribute.ts
  packages/phase2cli/src/commands/finalize.ts
  packages/phase2cli/src/commands/observe.ts
  packages/phase2cli/src/commands/setup.ts
  packages/phase2cli/src/lib/authorization.ts
  packages/phase2cli/src/lib/commands.ts
  packages/phase2cli/src/lib/constants.ts
  packages/phase2cli/src/lib/errors.ts
  packages/phase2cli/src/lib/paths.ts
  packages/phase2cli/src/lib/prompts.ts
  packages/phase2cli/src/lib/queries.ts
  packages/phase2cli/src/lib/utils.ts
  packages/phase2cli/types/index.ts
Labels: Test 🧪, Refactoring ♻
