Repository quadratic-funding/mpc-phase2-suite, pull requests merged in 2023-03, with the labels that each got.

#325 test (contribute)
  jest.json
  packages/actions/src/helpers/utils.ts
  packages/actions/src/types/snarkjs.d.ts
  packages/actions/test/data/artifacts/circuit-small_00000.zkey
  packages/actions/test/data/artifacts/division_00000.zkey
  packages/actions/test/data/artifacts/powersOfTau28_hez_final_02.ptau
  packages/actions/test/data/samples.ts
  packages/actions/test/e2e/01-setup.test.ts
  packages/actions/test/e2e/02-contribution.test.ts
  packages/actions/test/unit/authentication.test.ts
  packages/actions/test/unit/contribute.test.ts
  packages/actions/test/unit/security.test.ts
  packages/actions/test/unit/storage.test.ts
  packages/actions/test/utils/authentication.ts
  packages/actions/test/utils/index.ts
  packages/actions/test/utils/storage.ts
  packages/backend/test/index.test.ts
Labels: Test 🧪

#327 test(finalize): added unit tests for ceremony finalization
  packages/actions/test/data/circuit-small_verifier.sol
  packages/actions/test/data/circuit-small_vkey.json
  packages/actions/test/e2e/03-finalization.test.ts
  packages/actions/test/unit/finalize.test.ts
  packages/actions/test/utils/index.ts
  packages/actions/test/utils/storage.ts
Labels: Test 🧪

#332 feat(verification): added helper to extract artifacts from a zKey
  packages/actions/src/helpers/verification.ts
  packages/actions/src/index.ts
  packages/actions/test/data/circuit-small_00001.zkey
  packages/actions/test/unit/verification.test.ts
  packages/phase2cli/src/commands/finalize.ts
Labels: Feature 🪄

#335 feat(verification): added helper to generate/verify GROTH16 proofs
  packages/actions/src/helpers/verification.ts
  packages/actions/src/index.ts
  packages/actions/test/data/circuit_0000.zkey
  packages/actions/test/data/circuit_js/circuit.wasm
  packages/actions/test/data/verification_key_circuit.json
  packages/actions/test/unit/verification.test.ts
Labels: Feature 🪄

#337 feat(verification): verify that a zkey is valid
  packages/actions/src/helpers/verification.ts
  packages/actions/src/index.ts
  packages/actions/test/data/artifacts/bad_circuit_0000.zkey
  packages/actions/test/data/artifacts/circuit.circom
  packages/actions/test/data/artifacts/circuit.r1cs
  packages/actions/test/data/artifacts/notcircuit.circom
  packages/actions/test/data/artifacts/notcircuit.r1cs
  packages/actions/test/data/artifacts/notcircuit_0000.zkey
  packages/actions/test/unit/verification.test.ts
Labels: Feature 🪄

#353 ci: replace firebase project used to run e2e test by ci
  .github/workflows/test-ci-prod.yaml
Labels: DevOps ⚙

#356 ci: update backend before running e2e test
  .github/workflows/test-ci-prod.yaml
  packages/backend/.firebaserc
  packages/backend/package.json
Labels: DevOps ⚙

#348 feat(ceremony verification): implemented ceremony finalization verification
  package.json
  packages/actions/hardhat.config.ts
  packages/actions/package.json
  packages/actions/src/helpers/contracts.ts
  packages/actions/src/helpers/tasks.ts
  packages/actions/src/helpers/verification.ts
  packages/actions/src/index.ts
  packages/actions/src/types/index.ts
  packages/actions/src/types/solc.d.ts
  packages/actions/test/data/artifacts/circuit_vkey.json
  packages/actions/test/data/artifacts/inputs.json
  packages/actions/test/e2e/02-contribution.test.ts
  packages/actions/test/unit/contract.test.ts
  packages/actions/test/unit/contribute.test.ts
  packages/actions/test/unit/finalize.test.ts
  packages/actions/test/unit/security.test.ts
  packages/actions/test/unit/verification.test.ts
  packages/backend/package.json
  packages/backend/src/functions/ceremony.ts
  packages/backend/src/functions/circuit.ts
  packages/backend/src/functions/participant.ts
  packages/backend/src/functions/storage.ts
  packages/backend/src/functions/timeout.ts
  packages/backend/src/functions/user.ts
  packages/backend/types/solc.d.ts
  packages/phase2cli/package.json
  packages/phase2cli/src/commands/finalize.ts
  packages/phase2cli/types/solc.d.ts
  yarn.lock
Labels: Feature 🪄, Test 🧪, High Priority 🔥

#371 ci: use self-hosted runner to run `yarn test:dev`
  .github/workflows/test-ci-dev.yaml
Labels: DevOps ⚙
